import json
V = [
 ('People','保険契約者','Policyholder','Signs the contract and pays the premium.'),
 ('People','被保険者','Insured person','The person whose loss or injury is covered.'),
 ('People','保険会社','Insurance company','Pays claims. Paying claims is its own job, not the agent\'s.'),
 ('People','代理店','Agency / agent','Sells insurance for the insurance company.'),
 ('People','保険募集人','Insurance salesperson','Anyone who sells insurance (agency, its staff).'),
 ('People','使用人','Employee (of an agency)','Agency staff. Must be registered (届出) before selling.'),
 ('People','所属保険会社','Contracted insurance company','The company the agency sells for.'),
 ('People','顧客','Customer',''),
 ('People','被害者','Victim','The person hurt or damaged in an accident.'),
 ('People','失火者','Person who caused a fire','Not liable to neighbors unless gross negligence (失火責任法).'),
 ('People','相続人','Heir','Person who inherits.'),
 ('People','配偶者','Spouse','Husband or wife.'),
 ('People','内閣総理大臣','Prime Minister','Agencies register and report changes to the Prime Minister.'),
 ('Contract','締結','Concluding a contract','Making / signing the contract.'),
 ('Contract','保険契約申込書','Application form','Policyholder must check and sign it themselves.'),
 ('Contract','普通保険約款','General policy conditions','Standard rules of the contract.'),
 ('Contract','特約','Special clause / rider','Adds to or changes the general conditions. Has priority over them.'),
 ('Contract','告知義務','Duty of disclosure','Before the contract: answer the company\'s questions truthfully.'),
 ('Contract','通知義務','Duty of notification','After the contract: tell the company about changes.'),
 ('Contract','解除','Termination (by the company)','Company ends the contract, e.g. for disclosure violation.'),
 ('Contract','保険期間','Insurance period',''),
 ('Contract','満期日','Expiry date','Agent should help renew before this to avoid 無保険状態.'),
 ('Contract','無保険状態','Uninsured state','No insurance because the contract ended.'),
 ('Contract','引受','Underwriting','The company deciding to accept the risk.'),
 ('Money','保険料','Premium','Money the policyholder pays.'),
 ('Money','純保険料','Pure premium','Part of the premium used to pay claims.'),
 ('Money','付加保険料','Loading premium','Part used for company costs and profit.'),
 ('Money','保険金','Claim payment','Money the company pays after an accident.'),
 ('Money','保険金額','Sum insured','The maximum amount in the contract.'),
 ('Money','保険価額','Insurable value','The real value of the insured thing.'),
 ('Money','領収証','Receipt','Use the insurance company\'s official receipt only.'),
 ('Money','損害賠償額','Damages amount','Money paid to the other side for their loss.'),
 ('Principles','大数の法則','Law of large numbers','Many cases make accidents predictable.'),
 ('Principles','収支相等の原則','Principle of balance','Total pure premiums = total claim payments.'),
 ('Principles','公平の原則','Principle of fairness','Premium matches each person\'s risk.'),
 ('Principles','相互扶助','Mutual aid','"One for all, all for one."'),
 ('Principles','過失','Negligence / fault',''),
 ('Principles','重大な過失','Gross negligence',''),
 ('Principles','故意','Intention (on purpose)','Damage done on purpose is not paid.'),
 ('Principles','過失割合','Fault ratio','e.g. 70:30. You pay the OTHER side\'s damage × YOUR fault %.'),
 ('Products','火災保険','Fire insurance','Does not pay for earthquake damage.'),
 ('Products','地震保険','Earthquake insurance','Must be set with fire insurance. 30–50% of the fire amount.'),
 ('Products','自動車保険','Car insurance (voluntary)',''),
 ('Products','自賠責保険','Compulsory car liability insurance','Only covers injury/death of other people. Limit per victim.'),
 ('Products','対人賠償責任保険','Bodily injury liability','Pays for injuring or killing other people.'),
 ('Products','傷害保険','Personal accident insurance','Sudden, accidental, external injury (急激・偶然・外来).'),
 ('Products','個人賠償責任保険','Personal liability insurance','Daily-life accidents that hurt others.'),
 ('Products','海外旅行保険','Overseas travel insurance','Also covers treatment for illness.'),
 ('Products','後遺障害','Permanent disability',''),
 ('Rules','保険業法','Insurance Business Act','Main law for agents.'),
 ('Rules','重要事項説明書','Important matters document','Contains 契約概要 and 注意喚起情報.'),
 ('Rules','契約概要','Contract summary','Info needed to understand the product.'),
 ('Rules','注意喚起情報','Warning information','Info especially important for the customer to know.'),
 ('Rules','意向把握','Understanding customer wishes','Must check wishes and match the product to them.'),
 ('Rules','特別の利益','Special benefit','Discounts, cash back, gifts: prohibited.'),
 ('Rules','便宜供与','Giving favors','Excessive favors from the insurer to the agent are prohibited.'),
 ('Rules','推奨販売','Recommended sales','Agent must explain why it recommends a product.'),
 ('Rules','自己契約','Self-contract','Agency insuring itself. Must not be the main business.'),
 ('Rules','コンプライアンス','Compliance','Following laws AND company rules AND social norms.'),
 ('Rules','個人情報保護法','Personal Information Protection Act',''),
 ('Rules','犯罪収益移転防止法','Anti-money laundering act','Requires identity check (取引時確認).'),
 ('Rules','取引時確認','Identity check at transaction','For both individuals and companies.'),
 ('Rules','消費者契約法','Consumer Contract Act',''),
 ('Rules','金融サービス提供法','Financial Services Provision Act','Seller must explain important matters.'),
 ('Rules','景品表示法','Act against misleading representations','Ads and documents must not mislead.'),
 ('Rules','苦情','Complaint','Handle quickly and politely; report to the company.'),
 ('Liability','損害賠償責任','Liability for damages',''),
 ('Liability','不法行為責任','Tort liability','Liability for harming someone (no contract needed).'),
 ('Liability','債務不履行責任','Breach of contract liability',''),
 ('Liability','民法','Civil Code',''),
 ('Social & tax','健康保険','Health insurance (employees)',''),
 ('Social & tax','国民健康保険','National Health Insurance','Also covers work-related illness/injury.'),
 ('Social & tax','労災保険','Workers\' accident insurance','Basically no self-payment.'),
 ('Social & tax','地震保険料控除','Earthquake premium deduction','Income tax max 5万円; resident tax max 2.5万円.'),
 ('Social & tax','相続','Inheritance','Starts at the moment of death.'),
 ('Social & tax','法定相続分','Legal inheritance share','Spouse + children: 1/2 each.'),
 ('Social & tax','遺留分','Minimum guaranteed share','Heir can claim money if a will takes it away.'),
]
json.dump(V, open('vocab.json','w'), ensure_ascii=False)
